server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db-memelandia
    username: sa
    password: password
  application:
    name: meme-service-memelandia

custom:
  message: "Configuração centralizada para o Serviço do Meme."