server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db-memelandia
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: usuario-service-memelandia

custom:
  message: "Configuração centralizada para o Serviço do Usuário."